version: '1'

services:
  feature:
    container_name: extracao_brasileirao
    env_file:
      - .env
    build: .
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}